name: GitHub Actions Vercel Deployment

# Define Enviroment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Define When To Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Define Workflow Work
jobs:
  Vercel-Deploy-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Create PNPM_HOME directory and add it to PATH
      - name: Setup PNPM_HOME
        run: |
          mkdir -p $PNPM_HOME
          echo $PNPM_HOME >> $GITHUB_PATH

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: pnpm add -g vercel@canary

      # Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Build Project Artifacts
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy Project Artifacts to Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
